(() => {
'use strict';
const PATCH_VERSION='0.1.7', STATE_KEY='state.v1', PACKAGE_TYPE='training-journal-adaptive-extras';
let pendingPackage=null;
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
async function getState(){const s=await window.TJDB?.get?.(STATE_KEY);if(!s)return null;if(!Array.isArray(s.adaptiveExtras))s.adaptiveExtras=[];return s}
async function saveState(s){s.appVersion=PATCH_VERSION;await window.TJDB.set(STATE_KEY,s)}
function openModal(title,html,subtitle=''){const back=document.getElementById('modalBackdrop'),t=document.getElementById('modalTitle'),s=document.getElementById('modalSubtitle'),b=document.getElementById('modalBody');if(!back||!t||!b)return;t.textContent=title;s.textContent=subtitle;b.innerHTML=html;back.classList.remove('hidden');document.body.style.overflow='hidden'}
function closeModal(){document.getElementById('modalClose')?.click()}
function fmtDate(v){if(!v)return'—';const [y,m,d]=String(v).split('-').map(Number);return new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(y,(m||1)-1,d||1,12))}
function ensureImportUI(){
  if(!document.getElementById('tjProgramImport')){const i=document.createElement('input');i.type='file';i.accept='application/json,.json';i.id='tjProgramImport';i.hidden=true;document.body.appendChild(i);i.addEventListener('change',handleFile)}
  const hero=document.querySelector('#app .hero .actions');if(hero&&!hero.querySelector('[data-program-import]')){const b=document.createElement('button');b.className='button secondary';b.dataset.programImport='1';b.textContent='⇩ Importa programma';hero.appendChild(b)}
}
async function handleFile(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;try{const pkg=JSON.parse(await f.text());if(pkg.packageType!==PACKAGE_TYPE||!Array.isArray(pkg.adaptiveExtras))throw new Error('Formato non riconosciuto');pendingPackage=pkg;const rows=pkg.adaptiveExtras.map(x=>`<div class="list-item"><div class="avatar">↔</div><div class="grow"><h3>${esc(x.title||'Extra')}</h3><p>${esc(fmtDate(x.date))} · ${esc(x.duration||'')}</p></div><span class="badge">${esc(({high:'Alta',medium:'Media',low:'Bassa'})[x.priority]||'Media')}</span></div>`).join('');openModal('Importa programma',`<div class="card"><strong>${esc(pkg.title||'Programma')}</strong><p class="muted small">${esc(pkg.notes||'')}</p></div><div class="list">${rows}</div><div class="actions end"><button class="button ghost" data-program-cancel>Annulla</button><button class="button accent" data-program-confirm>Importa ${pkg.adaptiveExtras.length} Extra</button></div>`,'Gli Extra vengono aggiunti al calendario senza cancellare gli allenamenti esistenti.')}catch(err){alert('File programma non valido: '+err.message)}}
async function confirmImport(){if(!pendingPackage)return;const state=await getState();if(!state)return;let added=0,updated=0;for(const incoming of pendingPackage.adaptiveExtras){if(!incoming?.id||!incoming?.date||!incoming?.title)continue;const idx=state.adaptiveExtras.findIndex(x=>x.id===incoming.id);if(idx>=0){const old=state.adaptiveExtras[idx];state.adaptiveExtras[idx]={...old,...incoming,athleteChoice:old.athleteChoice||'',completed:old.completed||false,completedAt:old.completedAt||'',testResults:old.testResults||{}};updated++}else{state.adaptiveExtras.push({...incoming,athleteChoice:'',completed:false,testResults:{},importedAt:new Date().toISOString()});added++}}
  state.importedPrograms=Array.isArray(state.importedPrograms)?state.importedPrograms:[];state.importedPrograms.push({id:pendingPackage.programId||`pkg-${Date.now()}`,title:pendingPackage.title||'Programma',importedAt:new Date().toISOString(),count:pendingPackage.adaptiveExtras.length});await saveState(state);pendingPackage=null;closeModal();alert(`Programma importato: ${added} nuovi Extra${updated?`, ${updated} aggiornati`:''}.`);setTimeout(enhance,80)}
function fieldHtml(f,val){const common=`name="${esc(f.key)}" data-test-key="${esc(f.key)}"`;if(f.input==='textarea')return `<textarea ${common} rows="3" placeholder="${esc(f.placeholder||'')}">${esc(val??'')}</textarea>`;return `<input ${common} type="${f.input==='number'?'number':'text'}" ${f.input==='number'?'step="0.1"':''} value="${esc(val??'')}" placeholder="${esc(f.placeholder||'')}">`}
async function openTest(id){const state=await getState(),x=state?.adaptiveExtras?.find(a=>a.id===id);if(!x||!Array.isArray(x.testFields)||!x.testFields.length)return;const r=x.testResults||{};openModal('Registra test',`<form id="adaptiveTestForm" data-id="${esc(id)}"><div class="card"><strong>${esc(x.title)}</strong><p class="muted small">Registra solo dati realmente misurati. Nessun test deve arrivare a una ripetizione fallita.</p></div><div class="form-grid two">${x.testFields.map(f=>`<div class="field"><label>${esc(f.label)}${f.unit?` <span class="muted">(${esc(f.unit)})</span>`:''}</label>${fieldHtml(f,r[f.key])}</div>`).join('')}</div><div class="field"><label>Note del test</label><textarea name="_notes" rows="4" placeholder="Sensazioni, qualità tecnica, eventuale interferenza della classe...">${esc(r._notes||'')}</textarea></div><div class="actions end"><button type="button" class="button ghost" data-test-cancel>Annulla</button><button type="submit" class="button accent">Salva risultati</button></div></form>`,'I risultati restano associati a questo Extra')}
async function saveTest(form){const state=await getState(),x=state?.adaptiveExtras?.find(a=>a.id===form.dataset.id);if(!x)return;const fd=new FormData(form),out={...(x.testResults||{})};for(const f of x.testFields||[]){const v=String(fd.get(f.key)||'').trim();if(v!=='')out[f.key]=f.input==='number'?Number(v):v;else delete out[f.key]}out._notes=String(fd.get('_notes')||'').trim();out._updatedAt=new Date().toISOString();x.testResults=out;await saveState(state);closeModal();setTimeout(enhance,80)}
async function injectTestButtons(){const state=await getState();if(!state)return;document.querySelectorAll('.ae-card[data-ae-id]').forEach(card=>{const id=card.dataset.aeId,x=state.adaptiveExtras.find(a=>a.id===id);if(!x?.testFields?.length)return;const actions=card.querySelector('.ae-actions');if(actions&&!actions.querySelector('[data-test-open]')){const b=document.createElement('button');b.className='button ghost small';b.dataset.testOpen=id;b.textContent='◎ Registra test';actions.appendChild(b)}card.querySelector('.ae-test-summary')?.remove();const vals=x.testResults||{},bits=(x.testFields||[]).map(f=>vals[f.key]!==undefined&&vals[f.key]!==''?`${f.label}: ${vals[f.key]}${f.unit?` ${f.unit}`:''}`:'').filter(Boolean);if(bits.length){const d=document.createElement('div');d.className='ae-test-summary';d.innerHTML=`<strong>Test registrati</strong><span>${bits.map(esc).join(' · ')}</span>`;actions?.insertAdjacentElement('beforebegin',d)}})}
async function enhance(){ensureImportUI();await injectTestButtons()}
let t=null;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(enhance,80)}).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});
document.addEventListener('click',e=>{if(e.target.closest('[data-program-import]')){document.getElementById('tjProgramImport')?.click();return}if(e.target.closest('[data-program-confirm]')){confirmImport();return}if(e.target.closest('[data-program-cancel],[data-test-cancel]')){closeModal();return}const b=e.target.closest('[data-test-open]');if(b){openTest(b.dataset.testOpen);return}},true);
document.addEventListener('submit',e=>{if(e.target?.id==='adaptiveTestForm'){e.preventDefault();saveTest(e.target)}},true);
const style=document.createElement('style');style.textContent=`.ae-test-summary{margin-top:10px;padding:9px 10px;border-radius:10px;background:#f7f8f7;border:1px solid rgba(42,75,76,.09);display:flex;gap:6px;flex-direction:column}.ae-test-summary strong{font-size:.68rem;text-transform:uppercase;letter-spacing:.05em;color:var(--muted)}.ae-test-summary span{font-size:.72rem}`;document.head.appendChild(style);
setTimeout(enhance,120);console.info(`Training Journal Program Import ${PATCH_VERSION} loaded`);
})();
